<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Jellyfin.Plugin.Rippletube</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.Rippletube</RootNamespace>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Model" Version="10.10.7">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Controller" Version="10.10.7">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Web\*.html" />
    <EmbeddedResource Include="Web\*.js" />
    <EmbeddedResource Include="Web\*.css" />
  </ItemGroup>
</Project>
